### ISSUE TITLE
Readme should have compiling instructions

### ISSUE THREAD

**Issue by fine2006** [BiswasJishnu/OpenShare#12]
For a programming noobie the lack of compiling instruction could kill the will to help, it would be best if you include the recommended compiling instructions, as it helps with the projects a lot :)

**Comment by CTZxVULKAN** [comment]
Open the folder OpenShare/openshare you will find the instructions .
This project  is still in development once in production mode more instructions on how to set up stuff and for production will be added.
All instructions required to run this project in development mode is given.

**Comment by fine2006** [comment]
The help is appreciated, many thanks for that. :smile:
But the thing was I wanted to get these instructions to readme so that someone just checking out the project shouldn't just contact you to compile the project.
